name = "out"
defaultTargets = ["Out"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "Out"
leanOptions.weak.linter.style.nameCheck = false

[[require]]
name = "Sail"
git = "https://github.com/Chris-F5/lean-sail.git"
rev = "archsem-lean"